### PR TITLE
Release v0.6.1

### PR DESCRIPTION
**Pull request by nh916**
The main reason I am thinking of creating a release is that there needs to be a new patch for the Python SDK that must be released for it to work with the new API

### CODE REVIEW

**Comment by InnocentBug** [comment]
well, this shouldn't fail the test before we release, right?

**Comment by nh916** [comment]
@InnocentBug I agree it should not, but I have not checked the tests and am not sure if its a problem with the tests, the code, or something else

**Comment by dylanwal** [comment]
I agree with Ludwig about test. Can you look through the test and either update or delete the irrelevant test?

**Review by InnocentBug — APPROVED** [review]

**Comment by nh916** [comment]
@brili I think the current tests are being ran against the master branch of criptapp, is there a way we can run these tests against staging or development branch of criptapp as well.

**Comment by nh916** [comment]
Let me know if the changes I made need more comments, and I can add them in for clarity.

**Review by brili — APPROVED** [review]

**Pull request merged**
