### PR TITLE
README.md cosmetic updates

### PR DESCRIPTION
**Pull request by nh916**
added badges and made the links a bit cleaner

### CODE REVIEW

**Review by CVilla17 — DISMISSED** [review]

**Review by brili — DISMISSED** [review]

**Comment by brili** [comment]
is there a ticket for this?

**Comment by dylanwal** [comment]
I like the badges!
Can we get CRIPT logo/image added to the README too?

I would suggest keeping the 'pip install' aspect of the README.
we should look to emulate : https://github.com/pandas-dev/pandas

**Comment by nh916** [comment]
@brili there is no ticket for this, I started working on the SDK and thought this is an improvement that I can make quickly and created a PR for it

**Comment by nh916** [comment]
@dylanwal great suggestions! I implemented your suggestions. Please take a look at the README.md now and let me know what you think. 

I agree the logo makes it look much better. I went with the purple version and removed the background to make it transparent which I think works better on both light and dark mode

**Comment by brili** [comment]
@nh916 we need to restore the Prerequisites saying that python 3.9+ is required

**Comment by nh916** [comment]
@brili yeah I added that in one of the badges, but maybe thats not very clear since they're small, let me write it in the installation section too

**Review by dylanwal — APPROVED** [review]

**Review by brili — APPROVED** [review]

**Pull request merged**
